image: node:18

variables:
  DOCS_IMAGE: $CI_REGISTRY_IMAGE/docs

cache:
  paths:
    - .pnpm-store

stages:
  - build_docs
  - build_docker

build_docs:
  stage: build_docs
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - .next/

build_docker:
  stage: build_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - |
      cat <<EOF > Dockerfile
      FROM node:18-alpine AS builder
      WORKDIR /app
      RUN npm install -g pnpm
      COPY package*.json ./
      RUN pnpm install
      COPY . .
      RUN if [ ! -f next.config.js ]; then echo "const withNextra = require('nextra')({ theme: 'nextra-theme-docs', themeConfig: './theme.config.js' }); module.exports = withNextra();" > next.config.js; fi
      RUN pnpm run build

      FROM node:18-alpine
      WORKDIR /app
      RUN npm install -g pnpm
      COPY --from=builder /app/package*.json ./
      COPY --from=builder /app/.next ./.next
      COPY --from=builder /app/public ./public
      COPY --from=builder /app/node_modules ./node_modules
      COPY --from=builder /app/next.config.js ./next.config.js
      
      ENV NODE_ENV production
      
      CMD ["pnpm", "start"]
      EOF
    - docker build --pull -t $DOCS_IMAGE:$CI_COMMIT_REF_SLUG -t $DOCS_IMAGE:latest .
    - docker push $DOCS_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $DOCS_IMAGE:latest
  only:
    - main
